### ISSUE TITLE
alcyon not available on CRAN repository

### ISSUE THREAD

**Issue by akv-comp-arch** [acanth-is/alcyon#3]
Hey,
I tried installing alcyon on my machine but found that it is not available on the CRAN repository. Also, tried cloning it through github but was unsuccessful because of an error (code 128).  Are there any suggestions on how to install these? I am currently working on my dissertation and this has been problematic for me as I am new to github.

**Comment by pklampros** [comment]
The package has been taken down by CRAN due to some internal errors. I have pushed a new version (0.5) today, but until that goes through the process and lands into CRAN, you can install the previous version like this:
```
install.packages("devtools")
devtools::install_url("https://cran.r-project.org/src/contrib/Archive/alcyon/alcyon_0.4.0.tar.gz")
```
If this installation does not work then please further expand on the error you stumbled upon, and also specify the platform you are trying this on (Windows? MacOS? Linux?).

**Comment by pklampros** [comment]
@akv-comp-arch you should be able to install version 0.5.0 now, please check and let me know

**Comment by akv-comp-arch** [comment]
Yeah, I successfully installed the updated version. Thank you for the prompt response.
